<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>SerialWorkbench.ProtocolHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SerialWorkbench.Extensions.Abstractions/SerialWorkbench.Extensions.Abstractions.csproj" />
    <ProjectReference Include="../SerialWorkbench.Ipc/SerialWorkbench.Ipc.csproj" />
  </ItemGroup>
</Project>
