<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SerialWorkbench.Application/SerialWorkbench.Application.csproj" />
    <ProjectReference Include="../SerialWorkbench.Domain/SerialWorkbench.Domain.csproj" />
    <ProjectReference Include="../SerialWorkbench.Protocols/SerialWorkbench.Protocols.csproj" />
  </ItemGroup>
</Project>
